FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npx tsc -p tsconfig.build.json --skipLibCheck --noEmitOnError false || true
EXPOSE 4000
CMD ["node", "dist/main.js"]